
-- 1st step enums
CREATE TYPE public.user_kyc_status AS ENUM (
  'SUBMITTED',
  'VERIFIED',
  'REJECTED'
);

-- 2nd step tables
CREATE TABLE public.users (
  id uuid DEFAULT gen_random_uuid(),
  email text,
  password text,
  first_name text,
  last_name text,
  role text DEFAULT 'user',
  created_at timestamptz DEFAULT now(),
  avatar_url text,
  needs_onboarding boolean DEFAULT true,
  referral_code varchar
);

CREATE TABLE public.user_kyc (
  id uuid DEFAULT gen_random_uuid(),
  user_id uuid,
  status user_kyc_status DEFAULT 'SUBMITTED',
  id_front_url text,
  id_back_url text,
  submitted_at timestamptz DEFAULT now(),
  verified_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  id_document_type text,
  full_name text,
  first_name text,
  last_name text,
  address jsonb
);

CREATE TABLE public.mailroom_locations (
  id uuid DEFAULT gen_random_uuid(),
  name text,
  region text,
  city text,
  barangay text,
  zip text,
  total_lockers integer DEFAULT 0,
  code text
);

CREATE TABLE public.location_lockers (
  id uuid DEFAULT gen_random_uuid(),
  location_id uuid,
  locker_code text,
  is_available boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.mailroom_plans (
  id uuid DEFAULT gen_random_uuid(),
  name text,
  price numeric,
  description text,
  storage_limit numeric,
  can_receive_mail boolean DEFAULT true,
  can_receive_parcels boolean DEFAULT false,
  can_digitize boolean DEFAULT true
);

CREATE TABLE public.mailroom_registrations (
  id uuid DEFAULT gen_random_uuid(),
  user_id uuid,
  location_id uuid,
  plan_id uuid,
  locker_qty integer,
  months integer,
  notes text,
  created_at timestamp DEFAULT now(),
  full_name text,
  email text,
  mobile text,
  mailroom_status boolean DEFAULT true,
  mailroom_code text,
  auto_renew boolean DEFAULT true,
  order_id text,
  paid boolean DEFAULT false,
  paymongo_payment_id text
);

CREATE TABLE public.mailroom_assigned_lockers (
  id uuid DEFAULT gen_random_uuid(),
  registration_id uuid,
  locker_id uuid,
  assigned_at timestamptz DEFAULT now(),
  status text DEFAULT 'Normal'
);

CREATE TABLE public.mailroom_packages (
  id uuid DEFAULT gen_random_uuid(),
  registration_id uuid,
  package_type text,
  status text DEFAULT 'STORED',
  notes text,
  image_url text,
  mailroom_full boolean DEFAULT false,
  received_at timestamptz DEFAULT now(),
  locker_id uuid,
  release_proof_url text,
  release_to_name text,
  release_address text,
  release_address_id uuid,
  package_name text,
  package_photo text
);

CREATE TABLE public.mailroom_scans (
  id uuid DEFAULT gen_random_uuid(),
  package_id uuid,
  file_name text,
  file_url text,
  file_size_mb numeric DEFAULT 0,
  mime_type text,
  uploaded_at timestamptz DEFAULT now()
);

CREATE TABLE public.notifications (
  id uuid DEFAULT gen_random_uuid(),
  user_id uuid,
  title text,
  message text,
  type text,
  is_read boolean DEFAULT false,
  link text,
  created_at timestamptz DEFAULT timezone('utc', now())
);

CREATE TABLE public.paymongo_payments (
  id text,
  source_id text,
  order_id text,
  status text,
  amount integer,
  currency text,
  raw jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.referrals_table (
  referrals_id integer GENERATED BY DEFAULT AS IDENTITY,
  referrals_user_id uuid,
  referrals_referred_email varchar,
  referrals_service_type varchar,
  referrals_date_created timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.rewards_claims (
  id uuid DEFAULT gen_random_uuid(),
  user_id uuid,
  payment_method text,
  account_details text,
  amount numeric DEFAULT 500.00,
  status text DEFAULT 'PENDING',
  referral_count integer,
  created_at timestamptz DEFAULT now(),
  processed_at timestamptz,
  proof_path text
);

CREATE TABLE public.user_addresses (
  id uuid DEFAULT gen_random_uuid(),
  user_id uuid,
  label text,
  line1 text,
  line2 text,
  city text,
  region text,
  postal text,
  is_default boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  contact_name text
);
